#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
(
cd ${REPO_DIR}
helm uninstall local-postgresql -n pg-dfw-demo
helm uninstall foreign-postgresql -n pg-dfw-demo
kubectl delete pvc --all -n pg-dfw-demo
kubectl delete namespace pg-dfw-demo
)
